export const COMIC_GENRES = [
  'Acción',
  'Aventura',
  'Superhéroes',
  'Ciencia ficción',
  'Fantasía',
  'Terror',
  'Misterio',
  'Thriller',
  'Drama',
  'Romance',
  'Comedia',
  'Vida cotidiana',
  'Histórico',
  'Deportes',
  'Policial',
  'Postapocalíptico',
  'Cyberpunk',
  'Mecha',
  'Isekai',
  'Escolar',
  'Psicológico',
  'Distopía',
  'Steampunk',
  'Sobrenatural',
  'Parodia',
  'Musical',
  'Western',
  'Noir',
  'Tragedia',
  'Guerra',
  'Político',
]